language: bash
sudo: required

os:
    - linux

env:
  matrix:
  #- OS_TYPE=centos OS_VERSION=6
  - TRAVIS_OS_TYPE=centos TRAVIS_OS_VERSION=7
  - TRAVIS_OS_TYPE=debian TRAVIS_OS_VERSION=8

#dist: trusty
  
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo linux; fi
    - if [[ "$TRAVIS_OS_TYPE" == "centos" ]]; then export distro=Redhat             ; fi
    - if [[ "$TRAVIS_OS_TYPE" == "debian" ]]; then export distro=Debian             ; fi
    
script:
    - ./try_main_base.sh


#language: python
#
#before_install:
#  - export WHEELHOUSE=${HOME}/wheelhouse
#
#install:
#   # Needed to build wheels.
#   #- pip install tox
#   - pip install pyyaml
#
#script:
#  - ./try_main_base.sh
#
